.babelrc, .eslintrc.js, .gitignore, package.json, src/download-pool.js, test/pizza-guy.spec.js
- Add babel to tests.
- Enable lint script for test folder.
- Update pre-commit hook to run lint script.
=> Tests updates.

src/data-adapter.js, src/download-file.js, src/download-pool.js, src/pizza-guy.js, test/pizza-guy.spec.js
Adds ES2015 module syntax and cleans the code in the parts is possible without changing anything.
=> refactor(ES2015): Update code to ES2015

README.md
How to contribute, To Do List and Might Do List where added to the README file.
=> docs(README): Adding new sections to the README file

test/data-adapter.spec.js
=> test(data-adapter.spec.js): Adding spec for data-adapter

src/data-adapter.js
Now it's clear why we are doing that Array.from(new Set(arr)) thing
=> refactor(data-adapter): Creating removeDuplicates function

package.json, src/download-pool.js, test/download-pool.spec.js
Add tests for downloadPool.slice. More coverage :)
=> test(download-pool): Add unit tests for downloadPool.splice

.gitignore, README.md, demo/index.js, package.json
Add demo so people don't need to download the package into their projects to test its functionality or do some crazy`npm link`
For demo just run `npm run demo`
=> chore(demo): Add little demo.

wallaby.config.js
Add wallaby configuration if somebody wants to use that runner. Please take a look.
=> chore(test): Add wallaby configuration

src/download-file.js, test/download-file.spec.js
Every kind of file is right now being saved empty
closes #20
=> fix(download-file): Fixing issue # 20

README.md
I just added the javascript syntax on the code comments.
=> docs(README): Improve code block syntax comments.

src/download-file.js, test/download-file.spec.js
Bringing back old refactor from last week.
I already tested things with `npm run demo` and works ok. Maybe #19 was not specifically related to this refactor, but with the module itself.
@baldore  @andresdavid90 you _should_ double check though.
=> test(download-file.js): Add some unit tests

README.md
Missing syntax highlights in the README file added.
=> docs(README): Add missing syntax highlights

package.json, src/pizza-guy.js
Replaces error throwing with if blocks by invariant.
=> refactor(error-handling): Add inviariant for error handling

.eslintrc.json, package.json, test/data-adapter.spec.js, test/download-file.spec.js, test/download-pool.spec.js, test/http.spec.js, test/pizza-guy.spec.js
- Add one unit test for download-file.js
- Removed arrow functions on tests. See https://mochajs.org/#arrow-functions for reference.
- Updated eslint so it won't complain about ^ in the future.
=> download-file tests

.codecov.yml, .travis.yml, package.json
=> chore(travis): Adding check-coverage script

.travis.yml
That will add upcoming versions of Node
=> chore(travis.yml): Adding node to check the most stable version

test/download-file.spec.js, test/download-pool.spec.js, test/pizza-guy.spec.js
Making the tests to look good after running
=> refactor(test): Small changes

src/data-adapter.js, test/data-adapter.spec.js
If the module finds that the data set has duplicate entries, is going to report them on console.
=> test(data-adapter): Duplicates are now being tested

package.json, src/pizza-guy.js, test/pizza-guy.spec.js
The current error messages were not really giving full information about what was happening.
=> fix(pizza-guy): Changing error messages

.travis.yml, package.json
Supporting the latest and lts version of node. Using latest version of NPM.
fix #64
=> ci(.travis.yml): Updating travis.yml configuration

.babelrc, package-lock.json, package.json
=> build(package.json): Updating babel-preset-modern-node

test/download-file.spec.js
Somehow one of the async tests is failing just in the CI server. We are going to ignore that just
until we find the issue.
fix #68
=> test(download-file.spec.js): Ignoring one test in download-file
